var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var personImageSchema = new Schema({
    fullPath :              { type: String, required: true },
        //Oxford
    oxfordFaceID :      { type: String },
    oxfordDetectionDate :     { type: Date }
});

var personSchema = new Schema({
    name :              { type: String, required: true },
    directoryPath:      { type: String, required: true },
    faces :             { type: [personImageSchema] },
    //Oxford
    oxfordPersonID :         { type: String } //Generated by Oxford
});

module.exports = {
    person: mongoose.model('Person', personSchema),
    personImage : mongoose.model('PersonImage', personImageSchema)
};
