var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var personImageSchema = new Schema({
    path :              { type: String, required: true },
        //Oxford
    faceID :            { type: String},
    detectionDate :     { type: Date }
});

var personSchema = new Schema({
    projectID :         { type: String, required: true },
    name :              { type: String, required: true },
    faces :             { type: [personImageSchema], required: true},
    //Oxford
    personID :         { type: String, required: true } //Generated by Oxford
});

module.exports = {
    Person: mongoose.model('Person', personSchema),
    PersonImage : mongoose.model('PersonImage', personImageSchema)
};