var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var projectSchema = new Schema({
    name :          { type: String, required: true },
    //Oxford
    trainings :     { type: [Objectid], default: undefined},
    analized :      { type: Boolean, default: false }, //Generated by us to Oxford
    creationDate :  { type: Date, default: Date.now ()},
    info:           { type: String, default: "Needs a training to be added"}
});

module.exports = mongoose.model('Project', projectSchema);
