var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var ObjectId = mongoose.Schema.Types.ObjectId;

var projectSchema = new Schema({
    name :          { type: String, required: true },
    //Oxford
    trainings :     { type: [ObjectId], default: undefined},
    analized :      { type: Boolean, default: false }, //Generated by us to Oxford
    creationDate :  { type: Date, default: Date.now ()},
    info:           { type: String, default: "Needs a training to be added"},
    framesPath:     { type: String, default: undefined }
});

module.exports = mongoose.model('Project', projectSchema);
