var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var trainingSchema = new Schema({
    name :                { type: String, required: true },
    //Oxford
    trainedStatus :       { type: String, default: 'no' }, /* no, running, succeeded, failed */
    oxfordPersonGroupID : { type: String, default: 'undefined' }, //Generated by us to Oxford
    creationDate :        { type: Date, default: Date.now ()}
});

module.exports = mongoose.model('Training', trainingSchema);
